### ISSUE TITLE
Development plan for ORMIR-MIDS

### ISSUE THREAD

**Issue by DC-3T** [ormir-mids/ormir-mids#4]
## Overview
This 'umbrella' issue is used to keep track of tasks for developing ORMIR-MIDS. Please add any outstanding tasks or issues to the issue list below.

## Tasks
- [ ] https://github.com/ormir-mids/ormir-mids/issues/3
- [ ] Complete MRI data converters for main MSK MR sequences / vendors
- [ ] Finalise converter for DESS MRI data
- [ ] Finalise converters for CT / plain radiography data
- [ ] Convert GitHub pages site to a Jupyter book / MyST
- [ ] Update Jupyter notebooks for ORMIR-MIDS
- [ ] Develop automated tests for ORMIR-MIDS converters

**Comment by sbonaretti** [comment]
(Not sure this is the right place where to write this. Happy to move it wherever more pertinent!)
While running the **notebook** to transform images into the ORMIR-MIDS structure (to know what to write in the documentation!), I noticed some to-dos:
- [x] File names are still muscle-bids -> Changed to ormir-mids 
- [x] Internal links still contain muscle-bids -> Changed to ormir-mids 
- [ ] The executable called under *1.Usage: Run as executable* is still called `dcm2mbids`
- [ ] The imports and following code under *2. Usage: Import as python module* are still called `muscle_bids`
- [ ] The import in the dependencies is still called `muscle_bids`
